// <auto-generated />
namespace Web_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class appcontext111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appcontext111));
        
        string IMigrationMetadata.Id
        {
            get { return "201809020350468_appcontext1-1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
